# Generated by Django 3.2.3 on 2021-06-05 21:53
from django.db import migrations
from api.models import Timeslot

DAY_OF_WEEK = Timeslot.DAY_OF_WEEK
TIME_OF_DAY = Timeslot.TIME_OF_DAY


def add_timeslots(apps, schema_editor):
    Timeslot = apps.get_model("api", "Timeslot")
    for wod, weekday in DAY_OF_WEEK:
        for tod_index, tod in TIME_OF_DAY:
            Timeslot.objects.create(day=wod, time=tod_index)


def add_categories(apps, schema_editor):
    categories = [
        "Arqueologia",
        "Arte e Arquitectura",
        "Astronomia",
        "Biologia",
        "Gestão",
        "Química",
        "Ciência da comunicação",
        "Ciência da computação",
        "Economia",
        "Geografia",
        "História",
        "Línguas",
        "Matemática",
        "Filosofia",
        "Teologia & Estudos Religiosos",
        "Outra",
    ]

    KC = apps.get_model("api", "KnowledgeCategory")
    for category in categories:
        KC.objects.create(description=category)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_timeslots)]
