# Generated by Django 3.2.3 on 2021-06-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210605_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='academic_degree',
            field=models.IntegerField(choices=[(0, 'Licenciatura'), (1, 'Mestrado'), (2, 'Doutoramento'), (3, 'Nenhum')], default=3),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tues'), (2, 'Wed'), (3, 'Thur'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.IntegerField(choices=[(6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00')]),
        ),
    ]
