# Generated by Django 3.2.3 on 2021-06-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210605_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='job',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
