# Generated by Django 3.2.3 on 2021-06-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210605_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterhubuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'UNKNOWN')], default='U', max_length=100),
        ),
    ]
