# Generated by Django 3.2.3 on 2021-07-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_masterhubuser_gender'),
        ('api', '0006_auto_20210706_1854'),
    ]

    operations = [
    ]
